### ISSUE TITLE
transactional emails won't be sent

### ISSUE THREAD

**Issue by melaxon** [swissup/module-email#13]
When order is placed  no message will ne sent.
When I comment an order in backend I receive this popup:
`Zend\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided`

No records on Email Logs

"Contact us" works normally

magento 2.3.0
Swissup_Email just updated. previous version did the same

**Comment by 0m3r** [comment]
0. Did you try to disable Swissup_Email?
1. What is your full number version of Magento?
~~~ bash
cd [magento_root]
php bin/magento --version
git tag
~~~
I have seen a similar problem before with Magento 2.3.0 in core https://github.com/magento/magento2/issues/16938. There was a bug with the 'from' header.

It was fixed at Magento core.
https://github.com/magento/magento2/commit/7b9e807c8966308d173216d62f7ab40b11725353

**Comment by melaxon** [comment]
finally it's not swiss_email fault. When it is disabled the problem persists but no error message appears.

It was solved when I upgraded Magento to the latest version 2.3.1
By the way the latest 2.2.x is also okay
So it only happened in 2.3.0
